### ISSUE TITLE
Build VSCode extension for live preview

### ISSUE THREAD

**Issue by zenorocha** [resendlabs/react-email#15]
Inspiration:
* https://twitter.com/chriscoyier/status/1572644485628305409

Reference:
* https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode
* https://marketplace.visualstudio.com/items?itemName=DanielKnights.vscode-mjml

**Comment by EmersonGarrido** [comment]
Plus exemple : https://previewjs.com

**Comment by lucianodiisouza** [comment]
To be honest, I think that I have zero ability to build it, but I want to challenge myself 🤣

looking at the @EmersonGarrido  example, this opened issue continues valid @zenorocha  ?

**Comment by EmersonGarrido** [comment]
@lucianodiisouza It's open, I started to build something and I also have an example of an html preview extension in my open github.

**Comment by m-shaka** [comment]
Any updates? Please let me share my short survey.
I tried [@previewjs/cli](https://previewjs.com/docs/platforms/cli) to preview react-email components and it seems to work well, even though some errors are reported partly because an `html` tag is in another `html` tag.

And Preview.js is publishing its packages in npm so they can be used for react-email's extension.
https://www.npmjs.com/search?q=%40previewjs
