### ISSUE TITLE
Can we have a way to create output html as ejs template ?

### ISSUE THREAD

**Issue by arghyaiitb** [resendlabs/react-email#381]
Emails are generally sent by the backend, and most developers would use some kind of template engine in node or use template feature of email service provider. 

Since we are having a way to pass props to react emails, can we expand this to convert the props to be configured as an ejs template?

**Comment by zenorocha** [comment]
@arghyaiitb I see your point, but the problem is that every email service provider uses a different templating language. For example:

* Sendgrid uses Handlebars: https://docs.sendgrid.com/for-developers/sending-email/using-handlebars
* Postmark uses Mustachio: https://postmarkapp.com/support/article/1077-template-syntax

Adding support for Handlebars, Mustachio, EJS, etc is simply not scalable at this point.

**Comment by DarkPhoenix2704** [comment]
@arghyaiitb If you are using nest js, you can use this adapter to pass props
