### ISSUE TITLE
Container should render `<tbody>`

### ISSUE THREAD

**Issue by satazor** [resendlabs/react-email#529]
I'm getting the following react warning:

```
<tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
```

It seems the culprit is the `<Container>` component in my case, see. https://github.com/resendlabs/react-email/blob/5e8e465f89162bc0a7f4beeb2fc6062d77ce0b97/packages/container/src/container.tsx#L24
`<Section>` has the `tbody` element for example: https://github.com/resendlabs/react-email/blob/5e8e465f89162bc0a7f4beeb2fc6062d77ce0b97/packages/section/src/section.tsx#L28

Would you accept a PR adding it?

**Comment by bukinoshita** [comment]
Can you share your code?

**Comment by satazor** [comment]
I am not at home at the moment. I will try to give you a reproducible example.

**Comment by satazor** [comment]
Here's a reproducible example: https://github.com/satazor/react-email-tr-inside-table-warn

This doesn't help within `react-email`'s preview app because it uses `renderToStaticMarkup` which doesn't print these errors.

For some context, I'm creating my own preview app that allows previewing emails based on `react-email` + liquid. It's a Next.js app that doesn't use `renderToStaticMarkup` because HMR is near to impossible to do it with it. Instead, it renders the the email into a `<template>` tag. Then, I have a `MutationObserver` on the template node and updating an `<iframe>` srcDoc whenever the contents of the `<template>` changes. This way I got full HMR support: when the user edits the email, the email gets previewed instantly without a refresh.

**Comment by satazor** [comment]
@bukinoshita thanks for the fix. I leave here the Preview component code with the strategy I explained above. I ended up having to use a regular `<div>` instead of `<template>` due to React issues.

```js
import { renderLiquid } from '../../shared/render/index.js';
import { useEffect, useState } from 'react';
import { wrap } from 'lodash-es';
import ErrorScreen from '../../shared/react/error-screen/index.js';
import PropTypes from 'prop-types';

if (typeof window !== 'undefined') {
  // Ignore React warnings of <html> inside <div>
  console.error = wrap(console.error, (error, message, tag, parent, ...rest) => {
    if (tag === '<html>' && parent === 'div') {
      return;
    }

    error.call(console, message, tag, parent, ...rest);
  });
}

const useRender = (node, data) => {
  const [html, setHml] = useState();

  useEffect(() => {
    if (!node) {
      return;
    }

    const observer = new MutationObserver(() => setState(node.innerHTML));

    observer.observe(node, { attributes: true, characterData: true, childList: true, subtree: true });
    setState(node.innerHTML);

    return () => observer.disconnect();
  }, [node, data]);

  return html;
};

const emptyObject = {};

const Preview = ({ children }) => {
  const [node, setNode] = useState(null);
  const html = useRender(node);

  // To have full HMR support, `children` must be rendering regularly somehow. In this case, we render it on a `<div>`.
  // Then, by having a MutationObserver on the div node, we can be notified whenever it changes as part of a re-render.
  // When we get notified, we take it's HTML and render it using liquid to an iframe.
  return (
    <>
      <div ref={setNode} style={{ display: 'none' }}>
        {children}
      </div>

      {html && <iframe srcDoc={html} style={{ border: 'none', height: '100%', width: '100%' }} title="preview" />}
    </>
  );
};

Preview.propTypes = {
  children: PropTypes.element.isRequired
};

export default Preview;
```

**Comment by satazor** [comment]
Could you release a new version of `react-email` with the fix? 🙏

**Comment by kihonq** [comment]
> To give some context: I'm creating my own preview app that allows previewing emails based on react-email + _**liquid**_....

Hi @satazor ! I'm currently try to build my email using react-email for Auth0 where it uses Liquid Engine for templating it.
Came across your issue here where you mentioned liquid + react-email and wondering, if you are doing the similar thing for me to know how exactly are we handling the props and variables?
Thanks !

**Comment by JoaoOliveiraRocha** [comment]
Hi @kihonq I've inherited the project from @satazor so I can answer some of your questions.

## Variables:

We are passing directly the variables to the HTML as a Liquid's keys: since we're first getting the `html` from a React component and only then using the `parseAndRenderSync` we can have things directly like : 

```js
<CustomComponent label="{{ user.first_name | capitalize }}" description="Plain text here" />
```

that will create a element with a similar `node.innerHTML`:  
`<p style="font-family: &quot;Proxima Nova&quot;, Roboto, Helvetica, ...."><span>{{user.first_name | capitalize}}</span> - Plain text here</p>`

and that can be just called with:

```js
liquid.parseAndRenderSync(node.innerHTML, { customer: { first_name: "John" }}, { lenientIf: false, strictVariables: false });
```

and Liquid will do it's thing. This works even if any curious user tries something weird like having a first name `%}`.

### Note: "Application" specific variables.

We are using an email provider that contains a bunch of reserved liquid variables such as `unsubscribe_url`. Since we don't want them to be transformed in our email previewer tool we need to [register the tag](https://liquidjs.com/tutorials/register-filters-tags.html).

## Props

Sadly, no interaction between LiquidJS and JSX. I've been using "raw" LiquidJS for that.

```js
<Liquid  code={`
  {% case event.genericAttribute.counter | strip %}
    {% when '0' %}`} />
     
  <ResponsiveBanner src={src['0']}  (...)  />

  <Liquid code="{% when '1' %}" />
    
  <ResponsiveBanner src={src['1']}  (...)  />
      
<Liquid code="{% endcase %}" />
```
the `<Liquid>` component is just this:

```js
const Liquid = ({ code }) => <span dangerouslySetInnerHTML={{ __html: code }} data-liquid />;
```

There's no magic here unfortunately: LiquidJs support a nice number of features such as `for`, `switch - case`, and `capture`.

I guess it should be possible to do something similar and create a conditional render component

```js
const ConditionalRender = ({ condition, children }) => (
  <>
    <Liquid code={`{% if ${condition} %}`} />
    {children}
    <Liquid code="{% endif %}" />
  </>
);
```

and make use of `PropTypes` and other React helpers. But I didn't found it worth.

**Comment by kihonq** [comment]
Hi @JoaoOliveiraRocha !
Thank you for the prompt response (_unlike me_)
This is more than enough to get me started !
Thank you for being an awesome member of open-source community 🥂
