### ISSUE TITLE
npx create-email requires Node 18

### ISSUE THREAD

**Issue by EyMaddis** [resendlabs/react-email#612]
### Describe the Bug

I tried setting up the project, but it failed using Node 16, I tried again using Node 18 and it worked.
The failure was the following error:

```
> node -v
v16.14.2
> npx create-email@latest
Need to install the following packages:
  create-email@latest
Ok to proceed? (y) 
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /Users/mathis/.npm/_npx/5e64a2f331305744/node_modules/create-email/package.json
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

This is likely due to this like: https://github.com/resendlabs/react-email/blob/main/packages/create-email/src/index.js#L10

### Which package is affected (leave empty if unsure)

create-email

### Link to the code that reproduces this issue

uncessary

### To Reproduce

I used node version manager (nvm) to change the node version: https://github.com/nvm-sh/nvm

`nvm use 16`
then run
`npx create-email@latest`

observe the error

Try again with
`nvm use 18`
```
npx create-email@latest
(node:93600) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
⠋ Preparing files...
react-email-starter
├── emails
│   ├── notion-magic-link.tsx
│   ├── plaid-verify-identity.tsx
│   ├── static
│   │   ├── notion-logo.png
│   │   ├── plaid-logo.png
│   │   ├── plaid.png
│   │   ├── stripe-logo.png
│   │   ├── vercel-arrow.png
│   │   ├── vercel-logo.png
│   │   ├── vercel-team.png
│   │   └── vercel-user.png
│   ├── stripe-welcome.tsx
│   └── vercel-invite-user.tsx
├── package.json
├── readme.md
✔ React Email Starter files ready
```

### Expected Behavior

Should work with older version of Node.js or should document the requirement on the website.

### What's your node version? (if relevant)

16.14.2/v18.12.1

**Comment by JorbFreire** [comment]
I faced the same issue today.

I don't think it's too hard to make it run on v16 and it looks like a better solution than just setting the minimum compatible version of node to v18 in the documentation.

Maybe the intention of the authors for some reason is to not support projects before v18 of Node, but I don't think that's the case because the majority of the other packages require the minimum node version to be v16 like this one:
https://github.com/resendlabs/react-email/blob/main/packages/text/package.json#L33

The packages that I notice don't even mention the required Node version are the following:
- "Docs" (that I'm not sure we can call a package)

**Comment by JorbFreire** [comment]
I faced the same issue today.

I don't think it's too hard to make it run on v16 and it looks like a better solution than just setting the minimum compatible version of Node to v18 in the documentation.

Maybe the authors only intend to support Node v18 and later, but I don't think that's the case since the majority of the other packages require the minimum node version to be v16, like this one:
https://github.com/resendlabs/react-email/blob/main/packages/text/package.json#L33

The packages that don't even mention the required Node version are the following:
- ["Docs" (that I'm not sure we can call a package)](https://github.com/resendlabs/react-email/tree/main/docs)
- [body](https://github.com/resendlabs/react-email/blob/main/packages/body/package.jso)

**Comment by bukinoshita** [comment]
We should definitely support node 16 > as other packages. Let's fix this 🙏

**Comment by CryptoGraffe** [comment]
Still getting this when just trying to install the main package:

```
yarn add v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "jackspeak@2.1.1" is incompatible with requested version "jackspeak@^2.3.5"
[3/5] 🚚  Fetching packages...
error @react-email/container@0.0.10: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
